# Generated by Django 4.2.17 on 2025-04-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_membership_set",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="clubs_joined",
                through="clubs.ClubMembership",
                to="users.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clubmembership",
            unique_together={("profile", "club")},
        ),
    ]
