# Generated by Django 4.2.17 on 2025-05-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_eventownership"),
        ("clubs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="events_owned",
            field=models.ManyToManyField(
                blank=True,
                related_name="owning_clubs",
                through="events.EventOwnership",
                to="events.event",
            ),
        ),
    ]
