# Generated by Django 4.2.17 on 2025-05-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0003_club_events_owned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubmembership",
            name="is_active",
        ),
        migrations.AddField(
            model_name="clubmembership",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clubmembership",
            name="status",
            field=models.CharField(
                choices=[("requested", "Requested"), ("member", "Member")],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="clubmembership",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_membership_set",
                to="clubs.club",
            ),
        ),
    ]
