# Generated by Django 4.2.17 on 2025-05-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0004_remove_clubmembership_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="require_request",
            field=models.BooleanField(
                default=False, help_text="Require admin approval to join this club."
            ),
        ),
    ]
