# Generated by Django 4.2.17 on 2025-05-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0005_clubmembership_require_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubmembership",
            name="require_request",
        ),
        migrations.AddField(
            model_name="club",
            name="require_request",
            field=models.BooleanField(
                default=False, help_text="Require admin approval to join this club."
            ),
        ),
    ]
