# Generated by Django 4.2.17 on 2025-05-04 23:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0006_remove_clubmembership_require_request_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="members",
        ),
    ]
