# Generated by Django 4.2.17 on 2025-05-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("clubs", "0007_remove_club_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clubs_created",
                to="users.profile",
            ),
        ),
    ]
