# Generated by Django 4.2.17 on 2025-05-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_posttag_taggedposttag_alter_post_tags"),
        ("clubs", "0008_club_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="posts_owned",
            field=models.ManyToManyField(
                blank=True,
                related_name="owning_clubs",
                through="posts.PostOwnership",
                to="posts.post",
            ),
        ),
    ]
