# Generated by Django 5.2.1 on 2025-05-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0009_club_posts_owned"),
        ("events", "0006_eventtag_taggedeventtag_event_tags"),
        ("posts", "0004_posttag_taggedposttag_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="events_owned",
            field=models.ManyToManyField(
                blank=True,
                related_name="owning_clubs",
                through="events.EventOwnership",
                through_fields=("club", "event"),
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="posts_owned",
            field=models.ManyToManyField(
                blank=True,
                related_name="owning_clubs",
                through="posts.PostOwnership",
                through_fields=("club", "post"),
                to="posts.post",
            ),
        ),
    ]
