# Generated by Django 4.2.17 on 2024-12-29 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_group_channels"),
        ("uoftsocial", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupChannel",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
