# Generated by Django 4.2.17 on 2025-04-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_require_request_event_requirements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="Enter as [DD] [HH:[MM:[SS]]], e.g. 1 02:30 for 1 day 2h30m",
                null=True,
            ),
        ),
    ]
