# Generated by Django 4.2.17 on 2025-05-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
