# Generated by Django 4.2.17 on 2025-04-24 01:29

import digital_campus.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=digital_campus.storage_backends.MediaStorage(),
                upload_to="posts/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
