# Generated by Django 4.2.17 on 2025-04-24 18:52

import apps.posts.models
import digital_campus.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_image_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional. MP4/MOV/AVI/MKV, max 50 MB.",
                null=True,
                storage=digital_campus.storage_backends.MediaStorage(),
                upload_to="posts/%Y/%m/%d/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "mov", "avi", "mkv"]
                    ),
                    apps.posts.models.validate_video_size,
                ],
            ),
        ),
    ]
