# Generated by Django 4.2.17 on 2025-01-02 06:48

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatattachment",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_attachments/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="room_icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_room_icons/"
            ),
        ),
        migrations.AlterField(
            model_name="chatattachment",
            name="file",
            field=models.FileField(upload_to=chat.models.chat_attachment_path),
        ),
    ]
