# Generated by Django 4.2.17 on 2025-01-02 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_chatroom_chatmessage_chatattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="chat_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
