# Generated by Django 4.2.17 on 2025-05-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_remove_notification_verb_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOLLOW_REQUEST", "has requested to follow you"),
                    ("FOLLOW", "started following you"),
                    ("ACCEPT_FOLLOW_REQUEST", "accepted your follow request"),
                    ("EVENT_REQUEST", "requested to attend your event"),
                    ("EVENT_ACCEPT", "accepted your event request"),
                    ("EVENT_ATTEND", "is attending your event"),
                    ("CLUB_JOIN_REQUEST", "requested to join your club"),
                    ("CLUB_JOIN", "joined your club"),
                    ("CLUB_JOIN_ACCEPT", "accepted your club join request"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
