# Generated by Django 5.2.1 on 2025-05-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_alter_notification_type"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="type",
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("FOLLOW", "started following you"),
                    ("FOLLOW_REQUEST", "requested to follow you"),
                    ("ACCEPT_FOLLOW_REQ", "accepted your follow request"),
                    ("EVENT_REQUEST", "requested to attend your event"),
                    ("EVENT_ACCEPT", "accepted your event request"),
                    ("EVENT_ATTEND", "is attending your event"),
                    ("CLUB_JOIN_REQUEST", "requested to join your club"),
                    ("CLUB_JOIN", "joined your club"),
                    ("CLUB_JOIN_ACCEPT", "accepted your club-join request"),
                ],
                default="FOLLOW",
                editable=False,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_ct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_id",
            field=models.PositiveIntegerField(),
        ),
    ]
