# Generated by Django 5.2.1 on 2025-05-09 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_remove_notification_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
