# Generated by Django 5.2.1 on 2025-05-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="followers",
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="users.profile"
            ),
        ),
    ]
