# Generated by Django 5.2.1 on 2025-05-09 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("FOLLOW", "started following you"),
                            ("FOLLOW_REQUEST", "requested to follow you"),
                            ("ACCEPT_FOLLOW_REQ", "accepted your follow request"),
                            ("EVENT_REQUEST", "requested to attend your event"),
                            ("EVENT_ACCEPT", "accepted your event request"),
                            ("EVENT_ATTEND", "is attending your event"),
                            ("CLUB_JOIN_REQUEST", "requested to join your club"),
                            ("CLUB_JOIN", "joined your club"),
                            ("CLUB_JOIN_ACCEPT", "accepted your club-join request"),
                        ],
                        editable=False,
                        max_length=50,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("unread", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
