# Generated by Django 5.2.1 on 2025-05-19 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["name"], name="chat_chatro_name_b0f383_idx"),
        ),
    ]
