# Generated by Django 4.2.17 on 2025-01-02 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("uoftsocial", "__first__"),
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "current_courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_students",
                        to="uoftsocial.course",
                    ),
                ),
                (
                    "follow_requests",
                    models.ManyToManyField(
                        blank=True, related_name="requested_follows", to="users.profile"
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True, related_name="followed_by", to="users.profile"
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True, related_name="follows", to="users.profile"
                    ),
                ),
                (
                    "following_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pending_follow_requests",
                        to="users.profile",
                    ),
                ),
                (
                    "group_channels",
                    models.ManyToManyField(
                        blank=True,
                        related_name="channel_members",
                        to="chat.groupchannel",
                    ),
                ),
                (
                    "past_courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="former_students",
                        to="uoftsocial.course",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
