# Generated by Django 4.2.17 on 2024-12-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="group_channels",
            field=models.ManyToManyField(
                blank=True, related_name="channel_members", to="chat.groupchannel"
            ),
        ),
    ]
